const services=[["01","Cloud Architecture","AWS architecture, multi-account environments, governance, networking and modernization."],["02","Infrastructure","Enterprise compute, Linux, virtualization, storage and infrastructure modernization."],["03","Resilience & DR","High availability, disaster recovery, backup, replication and business continuity."],["04","Automation","Infrastructure as Code, cloud automation, deployment workflows and operational tooling."],["05","Software Solutions","Modern web applications, APIs and digital platforms designed around scalable architecture."],["06","Technology Consulting","Architecture assessment, technology strategy, modernization and technical advisory."]];
const projects=[["01","AWS Multi-Account Architecture","Enterprise AWS foundation with security, shared services and workload isolation.",["AWS","Governance","Cloud"]],["02","Secure AWS Web Platform","Private S3, CloudFront, OAC, WAF, Route 53 and ACM working as one secure web platform.",["CloudFront","S3","Security"]],["03","Enterprise RHEL HA","Pacemaker, Corosync, fencing and resilient application architecture.",["RHEL","HA","Linux"]],["04","Enterprise Storage Architecture","SAN/NAS architecture focused on performance, availability and resilience.",["Storage","SAN","NAS"]]];
const principles=[["Architecture First","Technology decisions follow business and architectural requirements."],["Security by Design","Security, governance and resilience are built into the platform from the beginning."],["Built to Scale","Architectures are designed for growth, automation and operational simplicity."]];
function Tags({items}:{items:string[]}){return <div className="tags">{items.map(x=><span key={x}>{x}</span>)}</div>}
export default function Home(){return <main>
<header className="nav"><a className="brand" href="#top"><span className="brand-mark">L</span>Logni</a><nav><a href="#services">Services</a><a href="#architecture">Architecture</a><a href="#projects">Projects</a><a href="#knowledge">Knowledge</a><a href="#about">About</a></nav><a className="nav-cta" href="#contact">Let&apos;s Talk ↗</a></header>
<section id="top" className="hero"><div><p className="eyebrow">CLOUD · INFRASTRUCTURE · ENGINEERING</p><h1>Engineering Reliable <em>Digital Infrastructure.</em></h1><p className="hero-text">We design and build secure, scalable and resilient technology platforms for modern businesses.</p><div className="actions"><a className="button primary" href="#projects">Explore Our Work →</a><a className="button secondary" href="#contact">Let&apos;s Talk ↗</a></div></div><div className="hero-visual"><div className="diagram"><b>USERS</b><i>↓</i><b>ROUTE 53</b><i>↓</i><b>CLOUDFRONT + WAF</b><i>↓</i><b>OAC · SIGV4</b><i>↓</i><b>PRIVATE S3</b></div></div></section>
<section className="capability-strip">{[["AWS","Cloud Architecture"],["INFRASTRUCTURE","Enterprise Platforms"],["STORAGE","SAN · NAS"],["RESILIENCE","HA · DR"],["AUTOMATION","IaC · DevOps"],["SECURITY","Governance · Protection"]].map(x=><div key={x[0]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</section>
<section id="services" className="section"><div className="section-heading"><p className="eyebrow">CAPABILITIES</p><h2>What We Build</h2><p>Practical engineering across cloud, infrastructure, resilience, automation and software.</p></div><div className="card-grid">{services.map(x=><article className="service-card" key={x[1]}><div className="card-top"><span>{x[0]}</span><span>↗</span></div><h3>{x[1]}</h3><p>{x[2]}</p><a href="#contact">Explore →</a></article>)}</div></section>
<section id="architecture" className="section architecture-section"><div className="section-heading"><p className="eyebrow">ARCHITECTURE LAB</p><h2>See how modern infrastructure is engineered.</h2><p>Reference architectures and engineering patterns built around security, resilience and operational simplicity.</p></div><div className="architecture-grid"><article className="architecture-card featured"><div className="mini">MANAGEMENT → SECURITY → SHARED SERVICES → WORKLOADS</div><p className="eyebrow">REFERENCE ARCHITECTURE</p><h3>AWS Enterprise Foundation</h3><p>Management, security, shared services and workload separation for a governed multi-account environment.</p><a href="#projects">Explore Architecture →</a></article><article className="architecture-card"><div className="stack"><b>ROUTE 53</b><b>CLOUDFRONT + WAF</b><b>OAC / SIGV4</b><b>PRIVATE S3</b></div><p className="eyebrow">REFERENCE ARCHITECTURE</p><h3>Secure AWS Web Platform</h3><p>CloudFront at the edge with WAF, ACM, OAC and a private S3 origin.</p><a href="#projects">Explore Architecture →</a></article><article className="architecture-card"><div className="ha"><b>RHEL 01</b><span>↔ PACEMAKER ↔</span><b>RHEL 02</b><small>Corosync · Fencing · VIP</small></div><p className="eyebrow">REFERENCE ARCHITECTURE</p><h3>RHEL High Availability</h3><p>Clustered application architecture with quorum, fencing and resilient service placement.</p><a href="#projects">Explore Architecture →</a></article></div></section>
<section className="feature"><div><p className="eyebrow">BUILT ON AWS</p><h2>Behind <em>GetLogni.com</em></h2><p className="feature-text">The website itself is an architecture case study: Route 53, CloudFront, WAF, ACM, OAC and a private S3 origin.</p><Tags items={["Route 53","CloudFront","WAF","ACM","OAC","S3"]}/><a className="text-link" href="#architecture">View Architecture →</a></div><div className="feature-diagram"><div>INTERNET</div><i>↓</i><div>ROUTE 53</div><i>↓</i><div>CLOUDFRONT · WAF</div><i>↓</i><div>OAC</div><i>↓</i><div>PRIVATE S3</div></div></section>
<section id="projects" className="section"><div className="section-heading"><p className="eyebrow">SELECTED PROJECTS</p><h2>Engineering in practice.</h2></div><div className="project-list">{projects.map(x=><article className="project-row" key={x[1]}><span className="project-number">{x[0]}</span><div><h3>{x[1]}</h3><p>{x[2]}</p><Tags items={x[3] as string[]}/></div><span className="project-arrow">↗</span></article>)}</div></section>
<section id="knowledge" className="knowledge"><div className="section-heading"><p className="eyebrow">KNOWLEDGE HUB</p><h2>Learn. Design. Engineer.</h2><p>Practical guides, architecture patterns and technical whitepapers.</p></div><div className="knowledge-grid">{[["AWS","Organizations · IAM · VPC · S3 · CloudFront · Route 53"],["Infrastructure","RHEL · Linux · VMware · Storage · SAN / NAS"],["Architecture","HA · DR · RPO / RTO · Hybrid Cloud · Governance"]].map(x=><div className="knowledge-card" key={x[0]}><span>EXPLORE</span><h3>{x[0]}</h3><p>{x[1]}</p><a href="#contact">Coming next →</a></div>)}</div></section>
<section id="about" className="section"><div className="section-heading"><p className="eyebrow">WHY LOGNI</p><h2>Technology. Architecture. Engineering.</h2><p>Logni focuses on practical technology solutions across cloud, infrastructure, storage, resilience and software engineering.</p></div><div className="principles">{principles.map((x,i)=><div key={x[0]}><span>0{i+1}</span><h3>{x[0]}</h3><p>{x[1]}</p></div>)}</div></section>
<section id="contact" className="contact"><p className="eyebrow">START A CONVERSATION</p><h2>Have a technology challenge?</h2><p>Let&apos;s discuss the architecture, infrastructure or digital solution you&apos;re trying to build.</p><a className="button primary" href="mailto:logni.team@gmail.com">Get in Touch ↗</a></section>
<footer><div><a className="brand" href="#top"><span className="brand-mark">L</span>Logni</a><p>Build. Scale. Simplify.</p></div><div className="footer-links"><a href="#services">Services</a><a href="#architecture">Architecture</a><a href="#projects">Projects</a><a href="#knowledge">Knowledge</a><a href="#about">About</a><a href="#contact">Contact</a></div><div className="footer-bottom"><span>© 2026 Logni. All rights reserved.</span><span>Built on AWS · Designed for scale.</span></div></footer>
</main>}